version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./solarwatch_backend
      dockerfile: Dockerfile
    container_name: spring_boot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_SHOW-SQL: true
      CODECOOL_APP_JWTSECRET: ${CODECOOL_APP_JWTSECRET}
      CODECOOL_APP_JWTEXPIRATIONMS: ${CODECOOL_APP_JWTEXPIRATIONMS}
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./solarwatch_frontend
      dockerfile: Dockerfile
    container_name: solar_frontend_container
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data: